plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: BDHU/minimalist

color-scheme: dark
favicon: false

logo: ./assets/images/me.jpg
title: Ronak Nahata
tagline: Personal Website
email: rnahata@asu.edu
description: >-
  “Enfant terrible, enfant terrible!” Betsy repeated.

sidebar:
  # - name: Hiking Journal
  #   icon: <i class="fa-solid fa-person-hiking"></i>
  #   link: /hiking
  # -
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/rizhu
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/rhu2001/
  - name: Resume
    icon: <i class="fa-solid fa-file-lines"></i>
    link: https://github.com/rizhu/Resume

github: [metadata]